name: Build and Push to JFrog

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Authenticate to JFrog via OIDC
        uses: jfrog/setup-jfrog-cli@v4
        with:
          oidc-provider-name: github
          oidc-audience: jfrog-github
        env:
          JF_URL: https://${{ vars.JFROG_REGISTRY }}

      - name: Configure JFrog Maven repos
        run: |
          jf mvn-config \
            --server-id-resolve=setup-jfrog-cli-server \
            --server-id-deploy=setup-jfrog-cli-server \
            --repo-resolve-releases=${{ vars.JFROG_MAVEN_REPO }}-release \
            --repo-resolve-snapshots=${{ vars.JFROG_MAVEN_REPO }}-snapshot \
            --repo-deploy-releases=${{ vars.JFROG_MAVEN_REPO }}-release \
            --repo-deploy-snapshots=${{ vars.JFROG_MAVEN_REPO }}-snapshot


      - name: Build with Maven
        env:
          JFROG_CLI_RELEASES_REPO: setup-jfrog-cli-server/extractors
        run: |
          jf mvn clean install -DskipTests \
            --build-name="${{ env.JFROG_CLI_BUILD_NAME }}" \
            --build-number=${{ env.JFROG_CLI_BUILD_NUMBER }} \
            --project=${{ vars.JFROG_PROJECT_KEY }}

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.JFROG_REGISTRY }}/${{ vars.JFROG_DOCKER_REPO }}/petclinic:${{ github.sha }} . 

      - name: Push Docker image
        run: |
          jf docker push ${{ vars.JFROG_REGISTRY }}/${{ vars.JFROG_DOCKER_REPO }}/petclinic:${{ github.sha }} \
            --project=${{ vars.JFROG_PROJECT_KEY }}

      - name: Publish build info
        run: |
          jf rt bp "${{ env.JFROG_CLI_BUILD_NAME }}" ${{ env.JFROG_CLI_BUILD_NUMBER }} \
            --project=${{ vars.JFROG_PROJECT_KEY }} \
            --collect-env \
            --collect-git-info

      - name: Run JFrog Xray Scan
        run: |
          jf docker scan ${{ vars.JFROG_REGISTRY }}/${{ vars.JFROG_DOCKER_REPO }}/petclinic:${{ github.sha }} \
            --project=${{ vars.JFROG_PROJECT_KEY }} \
            --fail=false

      - name: Scan build info
        run: |
          jf bs "${{ env.JFROG_CLI_BUILD_NAME }}" ${{ env.JFROG_CLI_BUILD_NUMBER }} \
            --project=${{ vars.JFROG_PROJECT_KEY }}