name: "Frogbot Scan Repository"
on:
  push:
    branches: [main]
permissions:
  id-token: write
  pull-requests: write
  contents: write
  security-events: write
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    name: Scan Repository (${{ matrix.branch }} branch)
    strategy:
      matrix:
        branch: ["main"]
    steps:
      - uses: jfrog/frogbot@v3
        env:
          #JFROG_CLI_LOG_LEVEL: "DEBUG"
          JF_URL: https://${{ vars.JFROG_REGISTRY }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
          JF_RELEASES_REPO: extractors
          JF_SKIP_AUTOFIX: false
        with:
          oidc-provider-name: github